# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
import vehicle_gateway_pb2 as vehicle__gateway__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in vehicle_gateway_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SensorServiceStub(object):
    """==============================================================================
    Service Definitions
    ==============================================================================

    Service for streaming sensor data from CARLA
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StreamSensorData = channel.unary_stream(
                '/vehicle_gateway.SensorService/StreamSensorData',
                request_serializer=vehicle__gateway__pb2.SensorSubscription.SerializeToString,
                response_deserializer=vehicle__gateway__pb2.SensorData.FromString,
                _registered_method=True)


class SensorServiceServicer(object):
    """==============================================================================
    Service Definitions
    ==============================================================================

    Service for streaming sensor data from CARLA
    """

    def StreamSensorData(self, request, context):
        """Subscribe to a stream of sensor data
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SensorServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StreamSensorData': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamSensorData,
                    request_deserializer=vehicle__gateway__pb2.SensorSubscription.FromString,
                    response_serializer=vehicle__gateway__pb2.SensorData.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'vehicle_gateway.SensorService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('vehicle_gateway.SensorService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SensorService(object):
    """==============================================================================
    Service Definitions
    ==============================================================================

    Service for streaming sensor data from CARLA
    """

    @staticmethod
    def StreamSensorData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/vehicle_gateway.SensorService/StreamSensorData',
            vehicle__gateway__pb2.SensorSubscription.SerializeToString,
            vehicle__gateway__pb2.SensorData.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class VehicleServiceStub(object):
    """Service for vehicle state and control
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StreamVehicleState = channel.unary_stream(
                '/vehicle_gateway.VehicleService/StreamVehicleState',
                request_serializer=vehicle__gateway__pb2.VehicleStreamRequest.SerializeToString,
                response_deserializer=vehicle__gateway__pb2.VehicleState.FromString,
                _registered_method=True)
        self.SendControlCommand = channel.unary_unary(
                '/vehicle_gateway.VehicleService/SendControlCommand',
                request_serializer=vehicle__gateway__pb2.VehicleControl.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)


class VehicleServiceServicer(object):
    """Service for vehicle state and control
    """

    def StreamVehicleState(self, request, context):
        """Stream the vehicle's kinematic state
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendControlCommand(self, request, context):
        """Send control commands to the vehicle
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_VehicleServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StreamVehicleState': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamVehicleState,
                    request_deserializer=vehicle__gateway__pb2.VehicleStreamRequest.FromString,
                    response_serializer=vehicle__gateway__pb2.VehicleState.SerializeToString,
            ),
            'SendControlCommand': grpc.unary_unary_rpc_method_handler(
                    servicer.SendControlCommand,
                    request_deserializer=vehicle__gateway__pb2.VehicleControl.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'vehicle_gateway.VehicleService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('vehicle_gateway.VehicleService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class VehicleService(object):
    """Service for vehicle state and control
    """

    @staticmethod
    def StreamVehicleState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/vehicle_gateway.VehicleService/StreamVehicleState',
            vehicle__gateway__pb2.VehicleStreamRequest.SerializeToString,
            vehicle__gateway__pb2.VehicleState.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendControlCommand(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vehicle_gateway.VehicleService/SendControlCommand',
            vehicle__gateway__pb2.VehicleControl.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class PerceptionServiceStub(object):
    """Service for perception data
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StreamDetectedObjects = channel.unary_stream(
                '/vehicle_gateway.PerceptionService/StreamDetectedObjects',
                request_serializer=vehicle__gateway__pb2.PerceptionRequest.SerializeToString,
                response_deserializer=vehicle__gateway__pb2.DetectedObjectList.FromString,
                _registered_method=True)
        self.StreamLanes = channel.unary_stream(
                '/vehicle_gateway.PerceptionService/StreamLanes',
                request_serializer=vehicle__gateway__pb2.PerceptionRequest.SerializeToString,
                response_deserializer=vehicle__gateway__pb2.LaneList.FromString,
                _registered_method=True)


class PerceptionServiceServicer(object):
    """Service for perception data
    """

    def StreamDetectedObjects(self, request, context):
        """Stream detected objects from the perception system
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamLanes(self, request, context):
        """Stream detected lanes
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PerceptionServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StreamDetectedObjects': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamDetectedObjects,
                    request_deserializer=vehicle__gateway__pb2.PerceptionRequest.FromString,
                    response_serializer=vehicle__gateway__pb2.DetectedObjectList.SerializeToString,
            ),
            'StreamLanes': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamLanes,
                    request_deserializer=vehicle__gateway__pb2.PerceptionRequest.FromString,
                    response_serializer=vehicle__gateway__pb2.LaneList.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'vehicle_gateway.PerceptionService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('vehicle_gateway.PerceptionService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PerceptionService(object):
    """Service for perception data
    """

    @staticmethod
    def StreamDetectedObjects(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/vehicle_gateway.PerceptionService/StreamDetectedObjects',
            vehicle__gateway__pb2.PerceptionRequest.SerializeToString,
            vehicle__gateway__pb2.DetectedObjectList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamLanes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/vehicle_gateway.PerceptionService/StreamLanes',
            vehicle__gateway__pb2.PerceptionRequest.SerializeToString,
            vehicle__gateway__pb2.LaneList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class PlanningServiceStub(object):
    """Service for planning and trajectory
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StreamTrajectory = channel.unary_stream(
                '/vehicle_gateway.PlanningService/StreamTrajectory',
                request_serializer=vehicle__gateway__pb2.PlanningRequest.SerializeToString,
                response_deserializer=vehicle__gateway__pb2.Trajectory.FromString,
                _registered_method=True)


class PlanningServiceServicer(object):
    """Service for planning and trajectory
    """

    def StreamTrajectory(self, request, context):
        """Stream the current planned trajectory
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PlanningServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StreamTrajectory': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamTrajectory,
                    request_deserializer=vehicle__gateway__pb2.PlanningRequest.FromString,
                    response_serializer=vehicle__gateway__pb2.Trajectory.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'vehicle_gateway.PlanningService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('vehicle_gateway.PlanningService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PlanningService(object):
    """Service for planning and trajectory
    """

    @staticmethod
    def StreamTrajectory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/vehicle_gateway.PlanningService/StreamTrajectory',
            vehicle__gateway__pb2.PlanningRequest.SerializeToString,
            vehicle__gateway__pb2.Trajectory.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class TripServiceStub(object):
    """Service for trip management (based on the original VehicleGateway)
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.VehicleLogin = channel.unary_unary(
                '/vehicle_gateway.TripService/VehicleLogin',
                request_serializer=vehicle__gateway__pb2.LoginRequest.SerializeToString,
                response_deserializer=vehicle__gateway__pb2.LoginResponse.FromString,
                _registered_method=True)
        self.SendEta = channel.unary_unary(
                '/vehicle_gateway.TripService/SendEta',
                request_serializer=vehicle__gateway__pb2.EtaRequest.SerializeToString,
                response_deserializer=vehicle__gateway__pb2.EtaResponse.FromString,
                _registered_method=True)
        self.SendStatus = channel.unary_unary(
                '/vehicle_gateway.TripService/SendStatus',
                request_serializer=vehicle__gateway__pb2.StatusRequest.SerializeToString,
                response_deserializer=vehicle__gateway__pb2.StatusResponse.FromString,
                _registered_method=True)
        self.SendArrive = channel.unary_unary(
                '/vehicle_gateway.TripService/SendArrive',
                request_serializer=vehicle__gateway__pb2.ArriveRequest.SerializeToString,
                response_deserializer=vehicle__gateway__pb2.ArriveResponse.FromString,
                _registered_method=True)
        self.StartTrip = channel.unary_unary(
                '/vehicle_gateway.TripService/StartTrip',
                request_serializer=vehicle__gateway__pb2.StartTripRequest.SerializeToString,
                response_deserializer=vehicle__gateway__pb2.StartTripResponse.FromString,
                _registered_method=True)
        self.CancelTrip = channel.unary_unary(
                '/vehicle_gateway.TripService/CancelTrip',
                request_serializer=vehicle__gateway__pb2.TripCommand.SerializeToString,
                response_deserializer=vehicle__gateway__pb2.CancelTripResponse.FromString,
                _registered_method=True)
        self.GetTripStatus = channel.unary_unary(
                '/vehicle_gateway.TripService/GetTripStatus',
                request_serializer=vehicle__gateway__pb2.TripStatusRequest.SerializeToString,
                response_deserializer=vehicle__gateway__pb2.TripStatusResponse.FromString,
                _registered_method=True)
        self.StreamTripUpdates = channel.stream_unary(
                '/vehicle_gateway.TripService/StreamTripUpdates',
                request_serializer=vehicle__gateway__pb2.TripUpdate.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)


class TripServiceServicer(object):
    """Service for trip management (based on the original VehicleGateway)
    """

    def VehicleLogin(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendEta(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendArrive(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StartTrip(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CancelTrip(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTripStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamTripUpdates(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TripServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'VehicleLogin': grpc.unary_unary_rpc_method_handler(
                    servicer.VehicleLogin,
                    request_deserializer=vehicle__gateway__pb2.LoginRequest.FromString,
                    response_serializer=vehicle__gateway__pb2.LoginResponse.SerializeToString,
            ),
            'SendEta': grpc.unary_unary_rpc_method_handler(
                    servicer.SendEta,
                    request_deserializer=vehicle__gateway__pb2.EtaRequest.FromString,
                    response_serializer=vehicle__gateway__pb2.EtaResponse.SerializeToString,
            ),
            'SendStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.SendStatus,
                    request_deserializer=vehicle__gateway__pb2.StatusRequest.FromString,
                    response_serializer=vehicle__gateway__pb2.StatusResponse.SerializeToString,
            ),
            'SendArrive': grpc.unary_unary_rpc_method_handler(
                    servicer.SendArrive,
                    request_deserializer=vehicle__gateway__pb2.ArriveRequest.FromString,
                    response_serializer=vehicle__gateway__pb2.ArriveResponse.SerializeToString,
            ),
            'StartTrip': grpc.unary_unary_rpc_method_handler(
                    servicer.StartTrip,
                    request_deserializer=vehicle__gateway__pb2.StartTripRequest.FromString,
                    response_serializer=vehicle__gateway__pb2.StartTripResponse.SerializeToString,
            ),
            'CancelTrip': grpc.unary_unary_rpc_method_handler(
                    servicer.CancelTrip,
                    request_deserializer=vehicle__gateway__pb2.TripCommand.FromString,
                    response_serializer=vehicle__gateway__pb2.CancelTripResponse.SerializeToString,
            ),
            'GetTripStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTripStatus,
                    request_deserializer=vehicle__gateway__pb2.TripStatusRequest.FromString,
                    response_serializer=vehicle__gateway__pb2.TripStatusResponse.SerializeToString,
            ),
            'StreamTripUpdates': grpc.stream_unary_rpc_method_handler(
                    servicer.StreamTripUpdates,
                    request_deserializer=vehicle__gateway__pb2.TripUpdate.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'vehicle_gateway.TripService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('vehicle_gateway.TripService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TripService(object):
    """Service for trip management (based on the original VehicleGateway)
    """

    @staticmethod
    def VehicleLogin(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vehicle_gateway.TripService/VehicleLogin',
            vehicle__gateway__pb2.LoginRequest.SerializeToString,
            vehicle__gateway__pb2.LoginResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendEta(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vehicle_gateway.TripService/SendEta',
            vehicle__gateway__pb2.EtaRequest.SerializeToString,
            vehicle__gateway__pb2.EtaResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vehicle_gateway.TripService/SendStatus',
            vehicle__gateway__pb2.StatusRequest.SerializeToString,
            vehicle__gateway__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendArrive(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vehicle_gateway.TripService/SendArrive',
            vehicle__gateway__pb2.ArriveRequest.SerializeToString,
            vehicle__gateway__pb2.ArriveResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StartTrip(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vehicle_gateway.TripService/StartTrip',
            vehicle__gateway__pb2.StartTripRequest.SerializeToString,
            vehicle__gateway__pb2.StartTripResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CancelTrip(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vehicle_gateway.TripService/CancelTrip',
            vehicle__gateway__pb2.TripCommand.SerializeToString,
            vehicle__gateway__pb2.CancelTripResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTripStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vehicle_gateway.TripService/GetTripStatus',
            vehicle__gateway__pb2.TripStatusRequest.SerializeToString,
            vehicle__gateway__pb2.TripStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamTripUpdates(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/vehicle_gateway.TripService/StreamTripUpdates',
            vehicle__gateway__pb2.TripUpdate.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class MapServiceStub(object):
    """Service for HD Map data
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetMapChunk = channel.unary_unary(
                '/vehicle_gateway.MapService/GetMapChunk',
                request_serializer=vehicle__gateway__pb2.MapRequest.SerializeToString,
                response_deserializer=vehicle__gateway__pb2.MapChunk.FromString,
                _registered_method=True)


class MapServiceServicer(object):
    """Service for HD Map data
    """

    def GetMapChunk(self, request, context):
        """Request a chunk of the HD map
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MapServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetMapChunk': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMapChunk,
                    request_deserializer=vehicle__gateway__pb2.MapRequest.FromString,
                    response_serializer=vehicle__gateway__pb2.MapChunk.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'vehicle_gateway.MapService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('vehicle_gateway.MapService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MapService(object):
    """Service for HD Map data
    """

    @staticmethod
    def GetMapChunk(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vehicle_gateway.MapService/GetMapChunk',
            vehicle__gateway__pb2.MapRequest.SerializeToString,
            vehicle__gateway__pb2.MapChunk.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
